### PR TITLE
WIP: Add torch intro notebooks

### PR DESCRIPTION
**Pull request by codingS3b**
This basically incorporates [our local repo](https://github.com/codingS3b/pytorch_intro/tree/biapol) into the course repo.

### CODE REVIEW

**Comment by codingS3b** [comment]
@psteinb please take this over during the next week.

**Comment by psteinb** [comment]
Will do, how does this related to #7 @jo-mueller ?

**Comment by haesleinhuepf** [comment]
Hi @codingS3b @psteinb @jo-mueller ,

let me know if this is ready to merge :-)

Big thanks!

Best,
Robert

**Comment by psteinb** [comment]
I got lagged behind due to some admin issues on our HPC platform. Let's merge this, so that we can eventually fix it. But the learners have the code.

**Comment by psteinb** [comment]
I see that merge conflicts have evolved. I could only removed them on Monday with @codingS3b. I hope that is OK.

**Pull request merged**
