### PR TITLE
clesperanto

### PR DESCRIPTION
**Pull request by StRigaud**

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
I've invited you as collaborator to the repository @StRigaud , so you can create branches ;-)

**Comment by StRigaud** [comment]
thks, I will continue with the fork and merge it later on as I started there, no big deal :)

**Comment by StRigaud** [comment]
@haesleinhuepf  I think i have covered the basis with the 3 first notebook:
- devices
- memory, push/pull
- operations and tips

Now  starting to work on filtering and segmentation, for now I am planning 
- basic 2D seg with voronoi_otsu
- 3D+t on the tribolium (wont have time to do something new :disappointed: )
- quantitative measurement (region props)
- benchmarking for the fun :rocket: 

If you think its too much or missing something, hit me up!

PS: I may need a bit more data in the repo than just the blobs, but we can see this when close to finish

**Comment by haesleinhuepf** [comment]
@StRigaud I hope everything is going well. Let us know when this is ready for review / merge ;-)

**Comment by StRigaud** [comment]
@haesleinhuepf  I'm open for reviews

I may have some typos, and surely missing some info (who made the data, links to extended documentation)

but let's have a first look at!

**Pull request closed without merging**
